name: api
on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
      - .github/workflows/api.yml
  pull_request:
    branches:
      - master
    paths:
      - 'api/**'
      - .github/workflows/api.yml
env:
  GOPATH: ${{ github.workspace }}/go
  PACKAGEPATH: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
jobs:
  protobuf-generate:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest]
    name: protobuf compile check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.PACKAGEPATH }}
      - uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ matrix.go-version }}
      - name: Compile protobufs
        working-directory: ${{ env.PACKAGEPATH }}
        run: make compile-protos
      - name: Ensure no diff when comparing generated and committed files
        working-directory: ${{ env.PACKAGEPATH }}
        run: ./scripts/api-ensure-no-diff.sh
