name: integration-tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  PACKAGEPATH: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
jobs:
  integration-tests:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.PACKAGEPATH }}
      - name: Install Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run configuration validator integration tests
        run: make integration-tests
        working-directory: ${{ env.PACKAGEPATH }}
